"""add_abandoned_to_playsessionstates

Revision ID: 1caaf38a33b9
Revises: 2daeb734a120
Create Date: 2026-09-27 23:44:10.327075

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1caaf38a33b9'
down_revision: Union[str, Sequence[str], None] = '2daeb734a120'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
