"""Initial models

Revision ID: 2daeb734a120
Revises:
Create Date: 2026-09-25 23:17:53.078205

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2daeb734a120'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('achievements',
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=False),
    sa.Column('condition_code', sa.String(length=100), nullable=False),
    sa.Column('icon', sa.String(length=255), nullable=True),
    sa.Column('sort_order', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.PrimaryKeyConstraint('code'),
    sa.UniqueConstraint('condition_code')
    )
    op.create_table('competencies',
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=False),
    sa.Column('sort_order', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('groups',
    sa.Column('id', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('type', sa.Enum('company', 'depot', 'brigade', name='groupstype'), nullable=False),
    sa.Column('parent_id', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['groups.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_groups_parent_id'), 'groups', ['parent_id'], unique=False)
    op.create_table('scenarios',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=False),
    sa.Column('version', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('difficulty', sa.String(length=20), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('start_node_key', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scenario_competencies',
    sa.Column('scenario_id', sa.String(length=50), nullable=False),
    sa.Column('competency_code', sa.String(length=50), nullable=False),
    sa.Column('weight', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.CheckConstraint('weight > 0', name='ck_scenario_competencies_weight_positive'),
    sa.ForeignKeyConstraint(['competency_code'], ['competencies.code'], ),
    sa.ForeignKeyConstraint(['scenario_id'], ['scenarios.id'], ),
    sa.PrimaryKeyConstraint('scenario_id', 'competency_code')
    )
    op.create_table('scenario_nodes',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('scenario_id', sa.String(length=50), nullable=False),
    sa.Column('node_key', sa.String(length=50), nullable=False),
    sa.Column('type', sa.Enum('start', 'dialogue', 'critical', 'ending_success', 'ending_fail', name='scenariostypes'), nullable=False),
    sa.Column('node_text', sa.String(length=1000), nullable=False),
    sa.Column('timer_sec', sa.Integer(), nullable=True),
    sa.Column('is_start', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.CheckConstraint('timer_sec > 0', name='ck_scenario_nodes_timer_positive'),
    sa.ForeignKeyConstraint(['scenario_id'], ['scenarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_scenario_nodes_one_start', 'scenario_nodes', ['scenario_id'], unique=True, postgresql_where=sa.text('is_start = true'))
    op.create_index(op.f('ix_scenario_nodes_scenario_id'), 'scenario_nodes', ['scenario_id'], unique=False)
    op.create_index('ix_scenario_nodes_scenario_node_unique', 'scenario_nodes', ['scenario_id', 'node_key'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=50), nullable=False),
    sa.Column('role', sa.Enum('conductor', name='usersroles'), server_default='conductor', nullable=False),
    sa.Column('group_id', sa.String(length=20), nullable=False),
    sa.Column('level', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('xp', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('total_score', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('total_score >= 0', name='ck_users_total_score_non_negative'),
    sa.CheckConstraint('xp >= 0', name='ck_users_xp_non_negative'),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_users_group_id'), 'users', ['group_id'], unique=False)
    op.create_table('choices',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('node_id', sa.Uuid(), nullable=False),
    sa.Column('choice_key', sa.String(length=50), nullable=False),
    sa.Column('choice_text', sa.String(length=255), nullable=False),
    sa.Column('effects', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('requirements', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('recommendation', sa.String(length=500), nullable=True),
    sa.Column('next_node_key', sa.String(length=50), nullable=False),
    sa.Column('sort_order', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('is_visible', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.ForeignKeyConstraint(['node_id'], ['scenario_nodes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_choices_node_id_choice_key', 'choices', ['node_id', 'choice_key'], unique=True)
    op.create_table('notifications',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('type', sa.Enum('new_scenario', 'challenge', 'expiring_points', 'achievement', name='notificationtypes'), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('body', sa.String(length=1000), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_notifications_user_id_read_at', 'notifications', ['user_id', 'read_at'], unique=False)
    op.create_table('play_sessions',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('scenario_id', sa.String(length=50), nullable=False),
    sa.Column('current_node_key', sa.String(length=50), nullable=False),
    sa.Column('state', sa.Enum('active', 'completed', 'failed', 'expired', name='playsessionstates'), server_default='active', nullable=False),
    sa.Column('loyalty', sa.Integer(), server_default=sa.text('100'), nullable=False),
    sa.Column('safety', sa.Integer(), server_default=sa.text('100'), nullable=False),
    sa.Column('score', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('version', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('deadline', sa.DateTime(timezone=True), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('loyalty >= 0 AND loyalty <= 100', name='ck_play_sessions_loyalty_range'),
    sa.CheckConstraint('safety >= 0 AND safety <= 100', name='ck_play_sessions_safety_range'),
    sa.CheckConstraint('score >= 0', name='ck_play_sessions_score_non_negative'),
    sa.CheckConstraint('version >= 0', name='ck_play_sessions_version_non_negative'),
    sa.ForeignKeyConstraint(['scenario_id'], ['scenarios.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_play_sessions_one_active', 'play_sessions', ['user_id', 'scenario_id'], unique=True, postgresql_where=sa.text("state = 'active'"))
    op.create_index('ix_play_sessions_scenario_id', 'play_sessions', ['scenario_id'], unique=False)
    op.create_index('ix_play_sessions_state', 'play_sessions', ['state'], unique=False)
    op.create_index('ix_play_sessions_user_id', 'play_sessions', ['user_id'], unique=False)
    op.create_table('user_competency_progress',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('competency_code', sa.String(length=50), nullable=False),
    sa.Column('score', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('score >= 0', name='ck_user_competency_progress_score_non_negative'),
    sa.ForeignKeyConstraint(['competency_code'], ['competencies.code'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'competency_code')
    )
    op.create_table('choice_competencies',
    sa.Column('choice_id', sa.Uuid(), nullable=False),
    sa.Column('competency_code', sa.String(length=50), nullable=False),
    sa.Column('delta', sa.Integer(), nullable=False),
    sa.CheckConstraint('delta >= -10 AND delta <= 15', name='ck_choice_competencies_delta_range'),
    sa.ForeignKeyConstraint(['choice_id'], ['choices.id'], ),
    sa.ForeignKeyConstraint(['competency_code'], ['competencies.code'], ),
    sa.PrimaryKeyConstraint('choice_id', 'competency_code')
    )
    op.create_table('session_events',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('node_key', sa.String(length=50), nullable=False),
    sa.Column('choice_id', sa.Uuid(), nullable=True),
    sa.Column('choice_key', sa.String(length=50), nullable=True),
    sa.Column('event_type', sa.Enum('choice', 'timeout', 'finish', 'fail', 'abandon', name='sessioneventtypes'), nullable=False),
    sa.Column('effects', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('competency_effects', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('loyalty_after', sa.Integer(), nullable=False),
    sa.Column('safety_after', sa.Integer(), nullable=False),
    sa.Column('score_delta', sa.Integer(), nullable=False),
    sa.Column('timer_sec', sa.Integer(), nullable=True),
    sa.Column('timer_left_sec', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('loyalty_after >= 0 AND loyalty_after <= 100', name='ck_session_events_loyalty_after_range'),
    sa.CheckConstraint('safety_after >= 0 AND safety_after <= 100', name='ck_session_events_safety_after_range'),
    sa.CheckConstraint('timer_left_sec IS NULL OR timer_left_sec >= 0', name='ck_session_events_timer_left_sec_non_negative'),
    sa.CheckConstraint('timer_sec IS NULL OR timer_sec >= 0', name='ck_session_events_timer_sec_non_negative'),
    sa.ForeignKeyConstraint(['choice_id'], ['choices.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['play_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_session_events_session_id_created_at', 'session_events', ['session_id', 'created_at'], unique=False)
    op.create_table('user_achievements',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('achievement_code', sa.String(length=50), nullable=False),
    sa.Column('unlocked_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['achievement_code'], ['achievements.code'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['play_sessions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'achievement_code')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_achievements')
    op.drop_index('ix_session_events_session_id_created_at', table_name='session_events')
    op.drop_table('session_events')
    op.drop_table('choice_competencies')
    op.drop_table('user_competency_progress')
    op.drop_index('ix_play_sessions_user_id', table_name='play_sessions')
    op.drop_index('ix_play_sessions_state', table_name='play_sessions')
    op.drop_index('ix_play_sessions_scenario_id', table_name='play_sessions')
    op.drop_index('ix_play_sessions_one_active', table_name='play_sessions', postgresql_where=sa.text("state = 'active'"))
    op.drop_table('play_sessions')
    op.drop_index('ix_notifications_user_id_read_at', table_name='notifications')
    op.drop_table('notifications')
    op.drop_index('ix_choices_node_id_choice_key', table_name='choices')
    op.drop_table('choices')
    op.drop_index(op.f('ix_users_group_id'), table_name='users')
    op.drop_table('users')
    op.drop_index('ix_scenario_nodes_scenario_node_unique', table_name='scenario_nodes')
    op.drop_index(op.f('ix_scenario_nodes_scenario_id'), table_name='scenario_nodes')
    op.drop_index('ix_scenario_nodes_one_start', table_name='scenario_nodes', postgresql_where=sa.text('is_start = true'))
    op.drop_table('scenario_nodes')
    op.drop_table('scenario_competencies')
    op.drop_table('scenarios')
    op.drop_index(op.f('ix_groups_parent_id'), table_name='groups')
    op.drop_table('groups')
    op.drop_table('competencies')
    op.drop_table('achievements')
    # ### end Alembic commands ###
